### ISSUE TITLE
PyPI releases for feature/v2

### ISSUE THREAD

**Issue by blester125** [dpressel/mead-baseline#430]
This is a place to track issues that should be addressed as we prepare feature/v2 to be merged into master and released onto pypi

- [x] https://github.com/dpressel/mead-baseline/issues/431

- [ ] https://github.com/dpressel/mead-baseline/issues/432

- [x] https://github.com/dpressel/mead-baseline/issues/433

- [x] https://github.com/dpressel/mead-baseline/issues/434

- [x] https://github.com/dpressel/mead-baseline/issues/435

- [x] https://github.com/dpressel/mead-baseline/issues/436

- [x] https://github.com/dpressel/mead-baseline/issues/437

- [x] https://github.com/dpressel/mead-baseline/issues/438

**Comment by dpressel** [comment]
I dont think #432 is listed on the milestone.  If it gets done, awesome, but the ticket as stated is complete
