### ISSUE TITLE
add pyproject.toml

### ISSUE THREAD

**Issue by blester125** [dpressel/mead-baseline#433]
The python community is using pyproject.toml to manage build time dependencies. We don't have any right now but we should move to this for future proofing. Also if we were to decide to build the proto buffs at build time (instead of pre compiling them and bundleing) we would need this file to manage the grpc install.

**Comment by dpressel** [comment]
We arent planning on using flit or poetry at this time, so the change required here is basically to copy the `pyproject.toml` from layers
