### ISSUE TITLE
Fix documentation link patches

### ISSUE THREAD

**Issue by blester125** [dpressel/mead-baseline#435]
A while ago I have some fixes to the main README when you run setup.py that would fix relative links to markdown files in the git repo into absolute github based links so that the links would work on pypi. This seems broken rn and should be fixed

**Comment by dpressel** [comment]
This should be fixed now.  I felt that the README was a bit overwhelming and linked the docs with an absolute link.  Now if somebody wants to read a book they can, otherwise they can just start using it
