### ISSUE TITLE
Update all tf models to pass `model.trainable_variables` to the optimizer

### ISSUE THREAD

**Issue by blester125** [dpressel/mead-baseline#493]
RN only the classifier passes the trainable variables to the optimizer which was needed for some post training updates. All the tasks should do this

**Comment by dpressel** [comment]
It looks like eager mode already does this, so this is just an issue for declarative mode, which by default uses all trainable variables:

```

        # All trainable variables, if specific variables are not specified.
        if variables is None:
            variables = tf.compat.v1.trainable_variables()

```
