### ISSUE TITLE
Update all tf models to correctly track the name scope

### ISSUE THREAD

**Issue by blester125** [dpressel/mead-baseline#494]
Right now some of the tagger models don't correctly handle names. For example the bLSTM part of the tagger ends up with variables named `blstm_encoder...` instead of `rnn_tagger/tag_sequence_model/blstm_encoder...` as we would have expected. See the classification models for expected behavior

**Comment by blester125** [comment]
There is also long standing weirdness where there are double feature names in embeddings like

```
...embedding_stack/char/char/...
```

**Comment by dpressel** [comment]
There are 2 open (competing) PRs that discuss the different ways of accomplishing this:

https://github.com/dpressel/mead-baseline/pull/498
https://github.com/dpressel/mead-baseline/pull/499

The tl;dr is that it kind of comes down to aesthetically what we'd like to see the name be, as Keras only cascades names from `call()` propagation

**Comment by dpressel** [comment]
This was solved by #542
