### ISSUE TITLE
How to reload models that use hub addons.

### ISSUE THREAD

**Issue by blester125** [dpressel/mead-baseline#496]
One problem with mead-hub, when you train a model that uses a vectorizer from mead hub the information to download it from the hub is removed when the class is saved into the output bundle for example I trained this sent-seg model using the vectorizer for hub and my vectorizers.json looked like this

```
[
 "sent_seg_context_window_vec"
]
```

When I try to reload the model it tries to load this module from the PYTHONPATH where it doesn't exist. We need to somehow keep the the information like `hub:v1:addon` in this vectorizer module definition if we want to support reloading models that have vectorizers that only live in hub.

There is probably a similar error for the `module` key that is saved into the `*.state` file when the model itself is a plug in

**Comment by dpressel** [comment]
Does it make sense to do like tensorflow and just have a pip install for the addons?

Users could try out the models from hub as they can now, but the addons could be simply installed?

**Comment by dpressel** [comment]
Once possible solution that is quite simple: https://github.com/dpressel/mead-baseline/pull/576

**Comment by dpressel** [comment]
Both examples might need a slight modification to support `vectorizers`  -- I was focused mainly on model support. I also think for vectorizers we might want to start moving away from pickle and just recording the state like we do for the others.

**Comment by dpressel** [comment]
I moved the vectorizer loading below the model loading so I believe this should be all right now for loading vectorizers from services, though the TF Serving code follows a different path which I didnt verify.
