### ISSUE TITLE
Test/update API examples

### ISSUE THREAD

**Issue by dpressel** [dpressel/mead-baseline#585]
- [x] analyze-calibration
- [x] bio_to_iobes
- [x] ~~classify-text-onnx~~ folded into `classify-text`
- [x] classify-text
- [x] convert_huggingface_checkpoints
- [x] create-ngram-embeddings
- [x] eager-lm (rename)
- [x] eager-lm-pytorch (rename)
- [x] eager-tagger
- [x] ed-text
- [x] ~~embed-sentence~~
- [x] embed-text
- [x] generate-mlm
- [x] iobes_result_to_bio
- [x] iob_to_bio
- [x] iob_to_iobes
- [x] layers-classify-pytorch (fixed in #617)
- [x] layers-classify-tf (fixed in #617)
- [x] lm-text
- [x] ~~lm-tf-estimator~~
- [x] pretrain-discrim
- [x] pretrain-lm-streaming
- [x] pretrain-lstlm-lm
- [x] pretrain-paired
- [x] pretrain-transformer-lm
- [x] response-selection
- [x] score-text
- [x] tag-text
- [x] ~~tag-text-onnx~~ (folded into `tag-text`)
- [x]  ~~tag-text-with-scores~~
- [x] ~~tensor-inputs~~ (get rid of this)
- [x] ~~tf-estimator~~ (get rid of this)
- [x] ~~tfkeras-train-from-scratch~~
- [x] tf-train-from-scratch
- [x] transformer-paired-responses

**Comment by dpressel** [comment]
A lot of these were broken toward the end of the 2.0 release and need updates.  Will get to them in the next few days

**Comment by blester125** [comment]
I vote we remove `tag-text-with-scores` it is an old addon that no one used and the scores provided weren't very principled

**Comment by dpressel** [comment]
> I vote we remove `tag-text-with-scores` it is an old addon that no one used and the scores provided weren't very principled

done
