### ISSUE TITLE
Performance issue in the difinition of zero_state, layers/eight_mile/tf/layers.py

### ISSUE THREAD

**Issue by DLPerf** [dpressel/mead-baseline#856]
Hello, I found a performance issue in the definition of `zero_state`, layers/eight_mile/tf/layers.py, [tf.zeros](https://github.com/dpressel/mead-baseline/blob/5c2c304c1bc5fce8fe95dafb484fbfecefea4fae/layers/eight_mile/tf/layers.py#L605) will be calculated repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop.

And the same issue exists in [tf.range(bsz)](https://github.com/dpressel/mead-baseline/blob/5c2c304c1bc5fce8fe95dafb484fbfecefea4fae/layers/eight_mile/tf/layers.py#L4308).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by dpressel** [comment]
hello, thanks for your interest in the project.  we are happy to accept PRs.

in the second case (during the beam decode), i dont see a good reason why we cant move it outside the block and, and i agree that may cause some efficiency gains (if `tf.autograph`) isnt smart enough to move it up already).  in the first case, the loop in the zeros function is only over the number of LSTM layers, not over time, so i would not expect any significant latency.  in fact for that case, it appears that Keras does the same thing:

https://github.com/keras-team/keras/blob/master/keras/layers/recurrent_v2.py#L1052
